python/pymanager

_msbuild.py
src/pymanager/appxmanifest.xml

These are required for Microsoft Store approval.

Update version calculation and remove unnecessary MSIX app

---

_msbuild.py

No longer a proof of concept!
Also removed a seemingly unused import.
A

Clarify project summary

---

.github/workflows/build.yml
README.md
pyproject.toml
tests/test_installs.py

Helps https://github.com/python/pymanager/issues/7.
Run tests with coverage,  and send to the terminal and Codecov, so we get reports like https://github.com/hugovk/pymanager/actions/runs/14727134371/job/41332386214#step:8:218 and https://app.codecov.io/gh/hugovk/pymanager/tree/coverage
Fix a reused test name that meant the test wasn't run, found from looking at test coverage results.

Add test coverage to CI

---

_msbuild.py
_msbuild_test.py
src/_native/misc.cpp
src/manage/pep514utils.py
tests/test_pep514utils.py

pep514utils now attempts to move existing registry entries if they appear invalid. This should reduce the likelihood of bad MSI uninstalls causing repeated warnings for the rest of time, at a small risk of corrupting (intentionally useless) entries.

Fixes #11 Detect and overwrite corrupt PEP 514 registry entries

---

src/manage/installs.py
tests/test_indexutils.py
tests/test_installs.py

Previously, if all matching runtimes were prereleases, the platform specifier would essentially be ignored. Now, when all matches are prereleases, we are okay with all matches after applying the platform filter being prereleases.

Fixes #24: Ensure platform override works on prereleases.

---

src/manage/list_command.py

```ps1con
PS> py list -f url -vv
...
[ERROR] INTERNAL ERROR: KeyError: 'url'
Traceback (most recent call last):
File "manage\__init__.py", line 50, in main
File "manage\commands.py", line 665, in execute
File "manage\list_command.py", line 300, in execute
File "manage\list_command.py", line 192, in format_bare_url
KeyError: 'url'
```
A

Fix internal error for ``py list --format url``

---

src/manage/list_command.py

Currently:
```ps1con
PS> py list --format spam
...
[ERROR] 'spam' is not a valid format; expect one of: csv, exe, id, json, jsonl, legacy, legacy-paths, prefix, table, url
```
However, the help output only lists `--format=<table,json,jsonl,id,exe,prefix>`. This PR removes the two 'legacy' entries, but keeps CSV and URL, as it might be useful to hint that these exist.
A

Remove legacy formatters from ``py list`` error output

---

src/manage/install_command.py
src/manage/pep514utils.py

Also cleans up some trivial TODOs

Fixes #59: Don't store source when it was the fallback.

---

_msbuild.py
src/pymanager/MsixAppInstallerData.xml

Adds MsixAppInstallerData to tweak the install UI.

---

_msbuild.py
src/manage/commands.py
src/manage/install_command.py
src/pymanager/_launch.cpp
src/pymanager/launcher.cpp
src/pymanager/main.cpp
src/pymanager/msi.wxs
tests/test_install_command.py

Also aligns some error messages for consistency.
Fixes #67

Add launcher executables for 32-bit and ARM64.

---

ci/repartition-index.yml
ci/upload.py
scripts/repartition-index.py
src/manage/tagutils.py
src/manage/urlutils.py
src/manage/verutils.py

Add index repartition script

---

.github/workflows/build.yml
_msbuild.py

This is expected to fail CI right now, but once we've released b1 then it can rerun and merge, after which we should be able to make a release that bundles 3.14.0b1.

Update PyManager to use 3.14.0b1 runtime

---

src/manage/commands.py
src/manage/config.py
src/manage/list_command.py
src/manage/logging.py
tests/conftest.py
tests/test_commands.py
tests/test_installs.py

Improves help output and testability of commands.

---

_msbuild.py
make-msix.py
src/pymanager/msi.wxs
src/pyshellext/pyshellext.def
src/pyshellext/shellext.cpp

Adds shell extension DLLs to MSI installer

---

src/manage/list_command.py

Re #86.
Point the user to `--help` rather than assuming the JSON format is the right option.

py list: When columns are truncated, direct the user to --help for more options

---

src/pymanager/appxmanifest.xml

Allow Windows 10 to ignore the shell extension registration.

---

src/manage/install_command.py

Fix installing the default runtime from a script with no shebang.

---

src/manage/config.py
src/manage/install_command.py
src/manage/installs.py
src/manage/list_command.py
src/manage/tagutils.py
src/manage/uninstall_command.py
tests/conftest.py
tests/test_install_command.py
tests/test_installs.py

Improves alias list messages after installation.

---

src/manage/pep514utils.py

Clarifications to PEP 514-related messages.

---

.github/workflows/build.yml
ci/release.yml
src/manage/arputils.py
src/manage/install_command.py
src/manage/pep514utils.py
src/manage/startutils.py
src/manage/uninstall_command.py
tests/conftest.py
tests/test_pep514utils.py

Pass through list of installs to warn about to shortcut implementations.

---

src/_native/winhttp.cpp
src/manage/config.py
src/manage/urlutils.py
src/pymanager/appxmanifest.xml

Few minor fixes for older OS.
Fixes #106

Block Windows Server 2019 from MSIX install.

---

.github/workflows/build.yml
ci/release.yml
src/manage/commands.py
src/manage/firstrun.py
tests/conftest.py
tests/test_firstrun.py

Update first launch test command

---

src/manage/install_command.py
src/pyshellext/shellext.cpp

Also fixes error refreshing installs.
Fixes #79

Disable IDLE menu while PyManager is working.

---

src/manage/uninstall_command.py
tests/conftest.py
tests/test_uninstall_command.py

Makes uninstall --purge also remove PATH entry.

---

src/pyshellext/shellext.cpp

Instead, we confirm that key deletion or insertion during enumeration produces weird behaviour, but should not crash.
Fixes #115

Disable mutex in shell extension.

---

src/_native/bits.cpp
src/_native/winhttp.cpp

Turns out the default "automatic" behaviour isn't automatic enough, so add the manual steps required to handle various configuration approaches.
Fixes #128

Add automatic proxy handling for WinHTTP and BITS

---

src/_native/helpers.cpp
tests/conftest.py
tests/test_shortcut.py
tests/test_urlutils.py

Fix message handling for errors raised from HRESULT or WinHTTP.

---

src/manage/install_command.py
tests/test_install_command.py

Generate python.exe and pythonw.exe in globals directory for default runtime.

---

src/manage/commands.py
src/manage/config.py
src/manage/install_command.py
src/pymanager.json

This 'fixes' issues people have where they want prerelease installer but not prerelease Python.
At 3.14's release, we'll remove the default config setting that installs 3-dev.
Fixes #122

Separate default install tag from default launch tag.

---

src/pymanager/_launch.cpp

Avoid overwriting inherited startup flags when launching Python.

---

.github/workflows/build.yml
ci/release.yml
src/pymanager.json

Build with Python 3.14 and install stable Python 3 by default

---

make.py
tests/test_arputils.py

added  test coverage for the `manage.arputils` module and removes an unused import.
Add 11 new tests for `manage.arputils` module
Remove unused `unlink` import from `make.py`

Add test coverage for arputils and remove unused import
